apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-qa
  namespace: qa
spec:
  selector:
    matchLabels:
      app: jenkins-demo-qa
  template:
    metadata:
      labels:
        app: jenkins-demo-qa
    spec:
      containers:
      imagePullSecrets:
      - name: regcred
      - image: xiaoshou0427/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo-qa
        env:
        - name: branch
          value: <BRANCH_NAME>
