apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-dev
  namespace: dev
spec:
  selector:
    matchLabels:
      app: jenkins-demo-dev
  template:
    metadata:
      labels:
        app: jenkins-demo-dev
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: xiaoshou0427/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
